### ISSUE TITLE
add_biaffine_layer() 에러 발생

### ISSUE THREAD

**Issue by februa22** [nlp-research/biaffineparser#9]
e8e6873 커밋에서 학습(`bash train.sh`) 실행 시 에러 발생해서 확인 중입니다.

@bart2001 함께 확인해주면 고맙겠습니다.

에러 메시지는 다음과 같습니다:

```python
Traceback (most recent call last):
  File "/Users/nhnent/miniconda3/envs/biaffineparser/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/nhnent/miniconda3/envs/biaffineparser/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nhnent/dev/workspace/biaffineparser/parser/parser.py", line 103, in <module>
    main(FLAGS)
  File "/Users/nhnent/dev/workspace/biaffineparser/parser/parser.py", line 95, in main
    word_embedding, pos_embedding)
  File "/Users/nhnent/dev/workspace/biaffineparser/parser/model.py", line 30, in __init__
    self.build()
  File "/Users/nhnent/dev/workspace/biaffineparser/parser/model.py", line 38, in build
    self.create_biaffine_layer()
  File "/Users/nhnent/dev/workspace/biaffineparser/parser/model.py", line 95, in create_biaffine_layer
    self.h_arc_dep, W_arc, self.h_arc_head, self.hparams.device, num_outputs=1, bias_x=True, bias_y=False)
  File "/Users/nhnent/dev/workspace/biaffineparser/parser/model.py", line 251, in add_biaffine_layer
    input1 = tf.concat((input1, tf.ones(batch_size, batch_len, 1)), axis=2)
  File "/Users/nhnent/miniconda3/envs/biaffineparser/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1669, in ones
    dtype = dtypes.as_dtype(dtype).base_dtype
  File "/Users/nhnent/miniconda3/envs/biaffineparser/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py", line 681, in as_dtype
    return _INTERN_TABLE[type_value]
TypeError: unhashable type: 'Dimension'
```

**Comment by februa22** [comment]
해당 에러는 픽스 완료. 다음 에러는 다른 이슈에 등록.
